# Generated by Django 2.0.1 on 2018-02-03 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('ArticleId', models.AutoField(primary_key=True, serialize=False)),
                ('ArticleRef', models.CharField(max_length=50)),
                ('ArticleName', models.CharField(max_length=50)),
                ('ArticlePrice', models.FloatField()),
            ],
            options={
                'db_table': 'Article',
            },
        ),
        migrations.CreateModel(
            name='ArticleType',
            fields=[
                ('ArticleTypeId', models.AutoField(primary_key=True, serialize=False)),
                ('ArticleTypeName', models.CharField(max_length=20)),
                ('ArticleTypeDesc', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'ArticleType',
            },
        ),
        migrations.CreateModel(
            name='ArticleUnit',
            fields=[
                ('ArticleUnitId', models.AutoField(primary_key=True, serialize=False)),
                ('ArticleUnitName', models.CharField(max_length=20)),
                ('ArticleUnitDesc', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'ArticleUnit',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productId', models.AutoField(primary_key=True, serialize=False)),
                ('productCode', models.CharField(max_length=50)),
                ('productName', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'Product',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('productCategoryId', models.AutoField(primary_key=True, serialize=False)),
                ('productCategoryName', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'ProductCategory',
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('productTypeId', models.AutoField(primary_key=True, serialize=False)),
                ('productTypeName', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'ProductType',
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('ProviderId', models.AutoField(primary_key=True, serialize=False)),
                ('ArticleFullName', models.CharField(max_length=50)),
                ('ArticleAddress1', models.CharField(max_length=80)),
                ('ArticleAddress2', models.CharField(max_length=80)),
                ('ArticlePhoneNum1', models.CharField(max_length=10)),
                ('ArticlePhoneNum2', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'Provider',
            },
        ),
        migrations.CreateModel(
            name='StoreInfo',
            fields=[
                ('storeInfoId', models.AutoField(primary_key=True, serialize=False)),
                ('storeName', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'StoreInfo',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='productTypeId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PyPerfumeStoreBackEndApp.ProductType'),
        ),
        migrations.AddField(
            model_name='article',
            name='ArticleTypeId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PyPerfumeStoreBackEndApp.ArticleType'),
        ),
        migrations.AddField(
            model_name='article',
            name='ArticleUnitId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PyPerfumeStoreBackEndApp.ArticleUnit'),
        ),
        migrations.AddField(
            model_name='article',
            name='ProviderId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PyPerfumeStoreBackEndApp.Provider'),
        ),
    ]
