# Generated by Django 2.0.1 on 2018-02-03 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PyPerfumeStoreBackEndApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='ArticleTypeId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PyPerfumeStoreBackEndApp.ArticleType'),
        ),
        migrations.AlterField(
            model_name='article',
            name='ArticleUnitId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PyPerfumeStoreBackEndApp.ArticleUnit'),
        ),
        migrations.AlterField(
            model_name='article',
            name='ProviderId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PyPerfumeStoreBackEndApp.Provider'),
        ),
    ]
