# Generated by Django 2.0.1 on 2018-02-03 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PyPerfumeStoreBackEndApp', '0002_auto_20180203_1208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='ArticleTypeId',
            new_name='ArticleType',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='ArticleUnitId',
            new_name='ArticleUnit',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='ProviderId',
            new_name='Provider',
        ),
    ]
