# Generated by Django 2.0.1 on 2018-02-03 12:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('PyPerfumeStoreBackEndApp', '0003_auto_20180203_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='ArticleCreationDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='ArticleMinQte',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='ArticleQte',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storeinfo',
            name='storeWebAppColor',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
