# Generated by Django 2.0.1 on 2018-02-03 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PyPerfumeStoreBackEndApp', '0004_auto_20180203_1241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='provider',
            old_name='ArticleAddress1',
            new_name='ProviderAddress1',
        ),
        migrations.RenameField(
            model_name='provider',
            old_name='ArticleAddress2',
            new_name='ProviderAddress2',
        ),
        migrations.RenameField(
            model_name='provider',
            old_name='ArticleFullName',
            new_name='ProviderFullName',
        ),
        migrations.RenameField(
            model_name='provider',
            old_name='ArticlePhoneNum1',
            new_name='ProviderPhoneNum1',
        ),
        migrations.RenameField(
            model_name='provider',
            old_name='ArticlePhoneNum2',
            new_name='ProviderPhoneNum2',
        ),
    ]
